### PR TITLE
Add add-404-page to master

### LINKED ISSUE #7: Add 404 page
**Describe the feature or change you'd like**
A 404 page should be added.

### PR DESCRIPTION
**Pull request by Aichnerc**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, there is no 404 error page. #7 

**What is the new behavior (if this is a feature change)?**
- A 404 error page has been added. #7 

**Other information**:
- The version has been updated to v1.2.2.

### CODE REVIEW

**Review by Aichnerc — COMMENTED** [review]
Looking good to me.

**Review by LucaAllmaier — APPROVED** [review]
Looks good.

**Review by schettn — APPROVED** [review]
LGTM!

**Review by sweggerat — APPROVED** [review]
looks fine

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Pull request merged**
