### PR TITLE
Improve security 1

### LINKED ISSUE #8: Migrate firebase
**Is your feature request related to a problem? Please describe.**
Currently, this homepage and our customer information service run on two different Firebase projects. 

**Describe the solution you'd like**
The two Firebase projects should be merged to one Firebase project, which makes communication between the two sites much easier.

### PR DESCRIPTION
**Pull request by Aichnerc**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently, the anonymous user login happens every time on function call.
- Currently, the user gets redirected to /thankyou after the contact has successfully been sent.
- Currently, the app uses its own Firebase project. #8 

**What is the new behavior (if this is a feature change)?**
- The anonymous login first checks if there is a user currently logged in. Only if none is present, the anonymous user is being logged in.
- The user gets redirected to /thankyou right away, with the contact creation happening asynchronous.
- The Firebase project has been migrated with that of our customer information service. #8 

**Other information**:
- The version has been updated to v1.2.1.

### CODE REVIEW

**Review by LucaAllmaier — CHANGES_REQUESTED** [review]
Wrong tab size again. Otherwise it looks fine.

**Review by Aichnerc — COMMENTED** [review]
Looks good.

**Review by LucaAllmaier — APPROVED** [review]
Looks good now

**Review by sweggerat — APPROVED** [review]
looks good

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Pull request merged**
